buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://plugins.gradle.org/m2/' }
        maven { url = 'https://maven.firstdark.dev/releases' }
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
        classpath 'org.parchmentmc:librarian:1.+'
        classpath 'com.hypherionmc.modutils:modpublisher:2.0.4'
    }
}

apply plugin: 'com.hypherionmc.modutils.modpublisher'
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'
if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/McJtyMods/MultiWorkspace/1.20_tech/gradletools.gradle'
}

group = 'mcjty.theoneprobe'
archivesBaseName = 'theoneprobe'
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

if (System.getenv('BUILD_NUMBER') != null) {
    version += "-${System.getenv('BUILD_NUMBER')}"
}

repos()
runs('theoneprobe')
jars('theoneprobe')

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    mc()
}

modpublisher(['baubles', 'tesla', 'redstone-flux'], [], [], [], [])

task apiJar(type: Jar) {
    classifier = 'api'
    from(sourceSets.main.output) {
        include 'mcjty/theoneprobe/api/**'
    }
}

artifacts {
    archives apiJar
}

publishing {
    publications.create('mavenJava', MavenPublication) {
        from components.java
        artifact apiJar

        artifactId = project.archivesBaseName
        pom {
            name = 'The One Probe'
            description = 'The One Probe'
            scm {
                url = 'https://github.com/McJtyMods/TheOneProbe'
                connection = 'scm:git:git@github.com:McJtyMods/TheOneProbe.git'
                developerConnection = 'scm:git:git@github.com:McJtyMods/TheOneProbe.git'
            }
            issueManagement {
                system = 'github'
                url = 'https://github.com/McJtyMods/TheOneProbe/issues'
            }
            licenses {
                license {
                    name = 'MIT'
                    distribution = 'repo'
                }
            }
            developers {
                developer {
                    id = 'McJty'
                    name = 'McJty'
                    roles = ['developer']
                }
            }
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                name = 'local'
                url = 'file://' + System.getenv('local_maven')
            }
        }
    }
}
